### ISSUE TITLE
Replace get_columns_in_table

### ISSUE THREAD

**Issue by joshtemple** [dbt-labs/segment#23]
With dbt 0.13.0, the adapter function `adapter.get_columns_in_table` is deprecated and will be removed. This package needs to use `adapter.get_columns_in_relation` instead.

The deprecated function is used in the model `segment_web_user_stitching`.

**Comment by clrcrl** [comment]
I _think_ it's actually coming through from `dbt_utils`, [here](https://github.com/fishtown-analytics/segment/blob/master/macros/cross-adapter-modeling/sessionization/segment_web_page_views__sessionized.sql#L141) we use the `dbt_utils.star` macro, and [that macro](https://github.com/fishtown-analytics/dbt-utils/blob/master/macros/sql/star.sql#L15) uses the `get_columns_in_table` macro.

I'm going to open an issue over on `utils` instead and close this one out :)

**Comment by clrcrl** [comment]
Never mind – there's already an open issue: https://github.com/fishtown-analytics/dbt-utils/issues/129
