### ISSUE TITLE
Configuration documentation for the package

### ISSUE THREAD

**Issue by shedd** [dbt-labs/segment#24]
It took a bit of trial and error to configure this package since the README is currently a bit light in this department 

Through digging around, I found the variable definitions in https://github.com/fishtown-analytics/segment/blob/master/dbt_project.yml#L16 that gave me enough to get this running.

I found that for the tests in this package to pass, I needed to do some de-duplication of my Segment source data. This meant that I created a new model (i.e. `segment_deduped_pages`) and pointing the `segment_page_views_table` var to it.

My primary `dbt_project.yml` config is thus:

```
models:
  vars:
    segment_page_views_table: "`dataset`.`analytics_intermediate`.`segment_deduped_pages`"
```

This works, but if I was working off of my DBT dev environment or a PR environment in DBT Cloud, this reference is was still pointing at the production `segment_deduped_pages` model, so any changes within the active schema weren't available for testing.

The Fishtown team (thanks @eogilvy12!) suggested that I might be able to `ref` the model here, as in:

```
models:
  vars:
    segment_page_views_table: "{{ ref('segment_deduped_pages') }}"
```

This was super helpful - while I should have found this myself, I wasn't able to locate any concrete guides to what is and is not parsed in `dbt_project.yml`.

Ultimately, this recommendation is close but, `dbt run` returns the following error:

```
Encountered an error:
Compilation Error in model stg_segment_pages (models/staging/segment/stg_segment_pages.sql)
  Required var 'segment_page_views_table' not found in config:
  Vars supplied to stg_segment_pages = {}
```

(`stg_segment_pages` is a model in my main schema)

In the end, the config needed to be:

```
models:
  vars:
    segment_page_views_table: "{{ ref('myschema', 'segment_deduped_pages') }}"
```

(where `myschema` is the name of your primary schema)

Hopefully this helps someone else.

As an idea, I find it useful how [Homebrew](https://brew.sh/) prints out the config next steps once you install a package. Perhaps after `dbt deps` is run, package-specific next steps could be printed?

**Comment by clrcrl** [comment]
@shedd – yes 100% agree that the installation instructions are... less than ideal at the moment!

I think for now, the quickest win would be an update to the README. If you feel compelled, I'd welcome a PR from you, otherwise I'll add this to my backlog :)

**Comment by shedd** [comment]
@clrcrl sure thing, I've put something together here: https://github.com/fishtown-analytics/segment/pull/26
