### ISSUE TITLE
tstamp issue with base view

### ISSUE THREAD

**Issue by murphmeister4000** [dbt-labs/segment#25]
For whatever reason segment sometimes has a handful of rows with a `timestamp` field years into the future, despite having an accurate `received_at` date. The base macro/view `segement_web_page_views` then returns these rows which causes any following incremental tables to not return any data.

**Comment by jslovin96** [comment]
hey, i am also experiencing this issue. has anyone looked into this at all?

**Comment by joellabes** [comment]
Thanks for opening this! https://github.com/fleetio/dbt-segment has adopted this package, so I'd recommend transferring this issue there if it is still a problem for you.
