### ISSUE TITLE
referrer_mapping fails to join if referrer includes "www."

### ISSUE THREAD

**Issue by chasleslr** [dbt-labs/segment#40]
### Issue
The current `{{segment_web_page_views() }}` macro creates the `referrer_host` field out of `referrer`. 

It is later used in `{{ segment_web_sessions__initial() }}` to join `data.referrer_mapping` to generate both `referrer_medium` and `referrer_source`.

This join fails if the initial `referrer` includes `www.`. For example, for `referrer` `https://www.pinterest.com/`, the resulting `referrer_host` is `www.pinterest.com` which then fails to join to any field in `referrer_mapping` -- the appropriate record being `pinterest.com`.

### Solution
Add `trim('www.' from referrer)` in `{{segment_web_page_views() }}` where `referrer_host` is generated.
While not part of this issue, the same logic should be added to `page_url_host` to remain consistent.

**Comment by chasleslr** [comment]
### Update:
I realized that `referrer_mapping` does include both versions host with and without leading `www.` for some values, but not all. For example, both `google.com` and `www.google.com` are included, but only `pinterest.com` is included, resulting in failure to join when `referrer_host` is `www.pinterest.com`.

**Comment by clrcrl** [comment]
I'd be happy to accept a PR that:
1. Removes the `www.` versions from `referrer_mapping`.
2. Trims out the `www.` for a cleaner join :) 
Let me know if you're interested in working on this! Otherwise we'll get to it at some point in the future 👀

**Comment by chasleslr** [comment]
Absolutely! I have to make those changes in my own dbt project anyway -- I might as well share with others! I'll submit a PR shortly.
