### ISSUE TITLE
Uniqueness error introduced in segment_web_page_views__sessionized model

### ISSUE THREAD

**Issue by sarahspooner** [dbt-labs/segment#65]
Hey I'm getting an error as follows meaning the page view id in the model "segment_web_page_views__sessionized" is not unique.;
unique_segment_web_page_views__sessionized_page_view_id

I have checked the inputs which are all unique so it seems this duplication is being introduced by the package.

**Comment by mrrobby** [comment]
I'm getting this too on Bigquery, `dbt==1.0.0`, `dbt-labs/segment==0.7.0`. 

The error that comes up is
```bash
UPDATE/MERGE must match at most one source row for each target row
```

with:
```json
"node_id": "model.segment.segment_web_page_views__sessionized"
```

Looking into the code, I see:
```sql
{{ config(
    materialized = 'incremental',
    unique_key = 'page_view_id',
    sort = 'tstamp',
    dist = 'page_view_id'
    )}}
```

But I have confirmed there ARE duplicate values for `page_view_id` in the resulting table, after one fresh run. Also, sort key and dist key seems redshift-specific. Does this support bigquery? I also am using some passthrough columns.

Any advice?

**Comment by MaximeLagresle** [comment]
Hey,

I'm also getting the same uniqueness error for my `page_view_id` . 
I have pretty much the same configs as @mrrobby :
`dbt==1.0.1` , `dbt-labs/segment==0.7.0` and running on BQ

I also HAVE duplicate values for `page_view_id`.

<img width="813" alt="image" src="https://user-images.githubusercontent.com/16308588/153223986-cf8049b7-ac16-468e-82d4-6b53ee87aac1.png">

**Comment by joellabes** [comment]
Any chance this is resolved by #81 and version 0.8.1?

**Comment by fred-boink** [comment]
Getting this on Snowflake:
Duplicate row detected during DML action
On 0.8.1
Is there any workaround for this?

**Comment by joellabes** [comment]
https://github.com/fleetio/dbt-segment has adopted this package, so I'd recommend transferring this issue there if it is still a problem for you.
