### ISSUE TITLE
Add column description to tables

### ISSUE THREAD

**Issue by mbrummerstedt** [dbt-labs/segment#68]
### Describe the feature
The columns in the tables created by the table should have descriptions to make it easier to understand the data in them.

### Describe alternatives you've considered
I have considered doing an override of your models, but I have not been able to get it to work for models, as it only seems to work for sources. 

### Additional context
I have added my descriptions as an md file, that you can use if you wish to. 
[docs.md](https://github.com/fishtown-analytics/segment/files/6727434/docs.md)

### Who will this benefit?
This will benefit all downstream users who should use the tables.

**Comment by joellabes** [comment]
Thanks for opening this! https://github.com/fleetio/dbt-segment has adopted this package, so I'd recommend transferring this issue there if it is still a problem for you.
