### ISSUE TITLE
Bad session data preventing incremental builds

### ISSUE THREAD

**Issue by jslovin96** [dbt-labs/segment#71]
### Describe the bug
Segment has been sending us a bad piece of data (session_start_at date is in the year 2026). This prevent any new data from being added during our incremental builds

### Steps to reproduce
N/A

### Expected results
I think this module should have a filter for only timestamps that are in the current_date (or even current_date+1) so that if a bad piece of data arises, it doesn't block the incremental build

**Which database are you using dbt with?**
- [ ] postgres
- [X] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

### Additional context
This is very high priority for my organization and we have no other recourse

### Are you interested in contributing the fix?
Sure, if that would help move things along. Thank you!

**Comment by joellabes** [comment]
Thanks for opening this - https://github.com/fleetio/dbt-segment has adopted this package, so I'd recommend transferring this issue there if it is still a problem for you.
