### ISSUE TITLE
Fix ambiguous column name warning on segment_web_sessions.sql

### ISSUE THREAD

**Issue by cecil185** [dbt-labs/segment#78]
When using this package, I got an ambiguous column name warning message from dbt_packages/segment/models/sessionization/segment_web_sessions.sql line 64 ["partition by blended_user_id"] and line 73 ["left join agg using (blended_user_id)"]

I believe line 64 can be fixed with "partition by sessions.blended_user_id"

... and line 73 can be fixed by joining with 'on' rather than 'using'  - "left join agg on sessions.blended_user_id = agg.blended_user_id"

Thank you!

**Comment by joellabes** [comment]
Thanks for opening this - https://github.com/fleetio/dbt-segment has adopted this package, so I'd recommend transferring this issue there if it is still a problem for you.
