### ISSUE TITLE
Adding static partitions

### ISSUE THREAD

**Issue by KolinMboorom** [dbt-labs/segment#82]
### Describe the feature
We have gotten large performance boosts to our models that run downstream of the segment package by setting static partitions. It would be great if we could get these in the package as well to streamline the sessions package and drive down run times. As it currently stands our sessions models are taking up 25% of our total current run time, and nothing else can run before these models finish. Adding this capability would be a massive help. As Jeremy laid out in this article, changing to static partitioning can be massively more efficient if your use case provides for it.

https://discourse.getdbt.com/t/benchmarking-incremental-strategies-on-bigquery/981

![image](https://user-images.githubusercontent.com/85885183/164270640-8905de3f-2869-45a6-86e2-6d2058fd266d.png)

### Describe alternatives you've considered
We've tried splitting the segment models into 8 different threads to increase run times, but because they all have to be rejoined before downstream models can be ran, that won't increase performance. We've also weighed trying to maintain our own segment package, but we would prefer to have the maintainability of it via having it managed by dbt labs

### Additional context
I believe this is big query specific.

### Who will this benefit?
This would help anyone who uses the segment package with BQ, and depends on customer sessions to drive a bulk of their data needs. Just applying this to a single model reduced our runtimes by a full 2 minutes!!

![image](https://user-images.githubusercontent.com/85885183/164732686-7a1c3852-680a-4e5d-b0c2-21fbd4ea73b0.png)

### Are you interested in contributing this feature?
I can contribute the idea :)

**Comment by KolinMboorom** [comment]
@joellabes Any chance I could get your thoughts on this?

**Comment by joellabes** [comment]
Hey @KolinMboorom, sorry for the silence here! I've been on parental leave but just got back. 

I'd welcome a PR to improve performance on BQ if you're still interested in submitting it 👍

**Comment by joellabes** [comment]
Followup - https://github.com/fleetio/dbt-segment has adopted this package - if you do make a PR, please make it against that repo instead!
