### ISSUE TITLE
Custom referrer mapping seed

### ISSUE THREAD

**Issue by fred-boink** [dbt-labs/segment#83]
### Describe the feature
Allow the referrer mapping seed to be swapped with a custom one by an environment variable. 

### Who will this benefit?
Anyone with domain specific referrers not mentioned in the current referrer mapping.

### Are you interested in contributing this feature?
Yes!

**Comment by fred-boink** [comment]
https://github.com/dbt-labs/segment/pull/84

**Comment by joellabes** [comment]
Thanks @fred-boink - this package has been adopted by https://github.com/fleetio/dbt-segment so please move your issue/PR there if you'd still like to contribute it
