### ISSUE TITLE
Update dbt_utils dependency to v0.9.x

### ISSUE THREAD

**Issue by cooley-hi** [dbt-labs/segment#86]
### Describe the feature

This package has a dependency on dbt_utils that restricts its version to <0.9.0. dbt_utils recently released compatibility release v0.9.x in preparation for their v1.0.0 release. It would be nice to be able to test against that release in preparation for the 1.0 release. [Slack announcement](https://getdbt.slack.com/archives/CU4MRJ7QB/p1658467817852129)

### Describe alternatives you've considered

I suppose it's not mission critical to be compatible with v0.9.x, but there are some breaking changes in v1.0 (they moved certain macros into dbt-core) that it would be nice to prepare for.

### Additional context
Is this feature database-specific? Which database(s) is/are relevant? Please include any other relevant context here.

### Who will this benefit?
What kind of use case will this feature be useful for? Please be specific and provide examples, this will help us prioritize properly.

dbt_utils is one of the most popular dbt packages. It seems compatibly with that package is more or less a necessity.

### Are you interested in contributing this feature?

Perhaps. I just don't have the time at the moment.

**Comment by cooley-hi** [comment]
Hi, bumping this to see if there's any headway on this? `dbt_utils` has already released `v1.0`. Thanks!

**Comment by joellabes** [comment]
Resolved by https://github.com/dbt-labs/segment/pull/89

Please note that this package is no longer being maintained by dbt Labs - you may want to change to https://github.com/fleetio/dbt-segment who have adopted it.
