### ISSUE TITLE
Follow-ups after package adoption

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/segment#95]
### Describe the feature

Things to do:
- [x] Hyperlink to new home
- [x] Determine how to handle open issues
- [ ] Archive repo

Update this to hyperlink to the new home:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/44704949/218507025-85d53b1a-f419-432c-8fdb-8c6715d6f026.png">

### Additional context

This link looks like it is already providing all the info we want:
https://hub.getdbt.com/dbt-labs/segment/latest/

e.g., it contains a link to the replacement package:
https://hub.getdbt.com/fleetio/dbt_segment/latest/

**Comment by joellabes** [comment]
I've done the first two, but not entirely sure that archiving the repo won't break existing installations from the Hub (it shouldn't, but I don't know one way or the other)

**Comment by security-dbtlabs** [comment]
Issue closed to prepare for Repository Archival
